services:
  ingestion:
    build:
      context: .
      dockerfile: ingestion/Dockerfile
    image: projeto-pos-ingestion:latest
    env_file:
      - .env
    volumes:
      - ./data:/data
    working_dir: /app

  duckdb-init:
    image: duckdb/duckdb:latest
    depends_on:
      ingestion:
        condition: service_completed_successfully
    volumes:
      - ./data:/data
      - ./duckdb:/db
      - ./sql:/sql
    entrypoint: ["/duckdb"]
    command:
      - /db/lakehouse.duckdb
      - -f
      - /sql/duckdb/create_bronze.sql

  dbt:
    build:
      context: ./transform
      dockerfile: Dockerfile
    image: projeto-pos-dbt:latest
    depends_on:
      duckdb-init:
        condition: service_completed_successfully
    volumes:
      - ./transform:/app
      - ./data:/data
      - ./duckdb:/db
    working_dir: /app
    environment:
      DBT_PROFILES_DIR: /app
    command: ["dbt", "run"]